vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.tabstop = 2
vim.opt.smartindent = true
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.termguicolors = true
vim.opt.hidden = true
vim.opt.scrolloff = 4
vim.opt.updatetime = 250
vim.opt.clipboard = "unnamedplus"
vim.g.mapleader = " "
