[window]
opacity = 0.85
decorations = "none"
padding = [10, 10]

[font]
family = "CaskaydiaMono Nerd Font Mono"
size = 13.0

[color]
background = "#192330"
foreground = "#cdcecf"
selection-background = "#2b3b51"
selection-foreground = "#cdcecf"
cursor = "#cdcecf"

ansi = [
  "#393b44", # black
  "#c94f6d", # red
  "#81b29a", # green
  "#dbc074", # yellow
  "#719cd6", # blue
  "#9d79d6", # magenta
  "#63cdcf", # cyan
  "#dfdfe0", # white
]

brights = [
  "#575860", # bright black
  "#d16983", # bright red
  "#8ebaa4", # bright green
  "#e0c989", # bright yellow
  "#86abdc", # bright blue
  "#baa1e2", # bright magenta
  "#7ad5d6", # bright cyan
  "#e4e4e5", # bright white
]

